name: stacked_meetup
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  get_it: ^4.0.4
  get: ^3.4.2
  auto_route: ^0.6.7
  injectable: ^1.0.2
  freezed_annotation: ^0.11.0+1
  json_serializable: ^3.3.0
  stacked_services: ^0.5.1
  intl: ^0.16.1
  stacked: ^1.7.5
  provider: ^4.3.1
  google_fonts: ^1.1.0
  http: ^0.12.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  auto_route_generator: ^0.6.7
  injectable_generator: ^1.0.3
  freezed: ^0.11.4
  build_runner: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
